FlipsideCrypto/gnosis-models

models/silver/silver__transactions.yml, tests/gnosis/test_silver__transactions_tx_gap.sql
ticketed with [PL-122](https://team-1612274056224.atlassian.net/browse/PL-122)
=> tx test failures

.gitignore, macros/tests/tx_block_count.sql, models/silver/silver__logs.sql, models/silver/silver__logs.yml, models/silver/silver__traces.sql
1. Added tx_gaps test to silver_logs
2. Changed unique key to tx_hash in silver_logs and silver_traces
3. Request chainwalkers to replay affected blocks `25347339, 25347340`
=> AN-2579/unique-key-tx-test

README.md, dbt_project.yml, macros/tags/add_database_or_schema_tags.sql, macros/tags/snowflake_tagging.sql, models/sushi/sushi__dim_dex_pools.sql, models/sushi/sushi__dim_kashi_pairs.sql, models/sushi/sushi__ez_borrowing.sql, models/sushi/sushi__ez_lending.sql, models/sushi/sushi__ez_swaps.sql
1. Implemented Snowflake tags via Macros and Model configs
2. Set `UPDATE_SNOWFLAKE_TAGS: True` and updated `readme.md` accordingly
3. Need to run `dbt run-operation` after merge
4. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2699?atlOrigin=eyJpIjoiMjBkNWI3ZTUyN2M4NDI4YzkzNDliYzRiOTZkNzExMGYiLCJwIjoiaiJ9)
=> AN-2699/snowflake-tags-gnosis

macros/run_sp_create_prod_clone.sql
- fixes dev refresh error caused by terraform role changes
=> dev clone now owned by new owner role

macros/sp_create_prod_clone.sql
1. Updated `sp_create_prod_clone` with new format/process 
2. Added var to fix issue with snowflake tagging on dev
3. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2728?atlOrigin=eyJpIjoiYjNiODU0ODFmMDlkNDIxMGI2ZmQ4NTI2MjE5MjkzMjciLCJwIjoiaiJ9)
=> AN-2728/dev-tag-fix-gno

.github/workflows/dbt_docs_update.yml, .github/workflows/dbt_run_adhoc.yml, .github/workflows/dbt_run_dev_refresh.yml, .github/workflows/dbt_run_incremental.yml, .github/workflows/dbt_test.yml
1. Modified workflows to reference `environment variables` instead of `secrets` for non-sensitive variables
2. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2756)
=> AN-2756/env-var-update

models/sushi/sushi__dim_kashi_pairs.yml, models/sushi/sushi__ez_borrowing.yml, models/sushi/sushi__ez_lending.yml
1. Added `Deprecating soon` to core sushi model descriptions
2. Removed tests from applicable yml files
=> AN-2785/sushi-tests-gnosis

.github/workflows/dbt_run_abi_refresh.yml, macros/create_udfs.sql, macros/python/keccak_udf.sql, macros/python/simple_event_name_udf.sql, macros/streamline/models.sql, models/silver/ABIs/silver__abis.sql, models/silver/ABIs/silver__abis.yml, models/silver/ABIs/silver__bytecode_abis.sql, models/silver/ABIs/silver__bytecode_abis.yml, models/silver/ABIs/silver__complete_event_abis.sql, models/silver/ABIs/silver__complete_event_abis.yml, models/silver/ABIs/silver__override_abis.sql, models/silver/ABIs/silver__proxies.sql, models/silver/ABIs/silver__user_verified_abis.sql, models/silver/ABIs/silver__user_verified_abis.yml, models/silver/ABIs/silver__verified_abis.sql, models/silver/ABIs/silver__verified_abis.yml, models/silver/silver__created_contracts.sql, models/silver/silver__created_contracts.yml, models/silver/streamline/_max_block_by_date.sql, models/silver/streamline/decoder/streamline__decode_logs_realtime.sql, models/sources.yml, packages.yml
- adds base decoding models 
- migrates to dbt 1.4
=> add base decoding models

models/silver/silver__blocks.sql, models/silver/silver__logs.sql, models/silver/silver__traces.sql, models/silver/silver__transactions.sql, models/silver/silver__transfers.sql, models/sushi/sushi__ez_borrowing.sql, models/sushi/sushi__ez_lending.sql, models/sushi/sushi__ez_swaps.sql
- Update all models using `hex_to_int` using `public` or `ethereum.public` schema to `utils` schema
- Excludes models with `enabled = false`
=> AN-3306/swap-public-to-utils

.github/workflows/dbt_run_streamline_history_adhoc.yml, .github/workflows/dbt_run_streamline_realtime.yml, .github/workflows/dbt_run_temp_backfill.yml, .github/workflows/dbt_run_temp_traces2_backfill.yml, models/silver/core/silver__blocks2.sql, models/silver/core/silver__confirmed_blocks.sql, models/silver/core/silver__logs2.sql, models/silver/core/silver__receipts.sql, models/silver/core/silver__traces2.sql, models/silver/core/silver__transactions2.sql, models/silver/core/silver__tx_count.sql, models/silver/streamline/core/history/streamline__debug_traceBlockByNumber_history.sql, models/silver/streamline/core/history/streamline__qn_getBlockWithReceipts_history.sql, packages.yml
1. silver layer for core streamline models
2. adds temp backfill workflows
3. Requires FR and backfill for traces, estimated ~15hrs
=> AN-3367/gno-silver-streamline

.github/workflows/dbt_run_incremental_non_realtime.yml, .github/workflows/dbt_run_streamline_chainhead.yml, .github/workflows/dbt_run_streamline_decoder.yml
=> refresh rate

README.md, dbt_project.yml, models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql
1. Adds new variable to reload records in complete model w/o FR
2. Docs in README
=> curated-heal-var

models/silver/defi/lending/aave/silver__aave_tokens.sql, models/silver/defi/lending/aave/silver__aave_tokens.yml, models/silver/defi/lending/agave/silver__agave_tokens.yml, models/silver/defi/lending/realt/silver__realt_tokens.sql, models/silver/defi/lending/realt/silver__realt_tokens.yml, models/silver/defi/lending/spark/silver__spark_tokens.sql, models/silver/defi/lending/spark/silver__spark_tokens.yml
```
dbt run -m models/silver/defi/lending/aave/silver__aave_tokens.sql models/silver/defi/lending/agave/silver__agave_tokens.sql models/silver/defi/lending/realt/silver__realt_tokens.sql models/silver/defi/lending/spark/silver__spark_tokens.sql --full-refresh
```
=> AN-4556/add-aave-token-model-tests 

models/bronze/api_udf/bronze_api__contract_abis.sql, models/bronze/api_udf/bronze_api__token_reads.sql, models/silver/defi/bridge/hop/silver_bridge__hop_ammwrapper.sql, models/silver/defi/bridge/hop/silver_bridge__hop_l2canonicaltoken.sql, models/silver/defi/dex/balancer/silver_dex__balancer_pools.sql, models/silver/defi/dex/curve/silver_dex__curve_pools.sql, models/sources.yml, package-lock.yml, packages.yml
`dbt run -s livequery_models.deploy.core --vars '{DROP_UDFS_AND_SPS: true}' -t prod && dbt run -s livequery_models.deploy.core --vars '{UPDATE_UDFS_AND_SPS: true}' -t prod`
=> vault secrets

README.md, dbt_project.yml, models/gold/defi/defi__ez_bridge_activity.sql, models/gold/defi/defi__ez_dex_swaps.sql, models/silver/core/silver__transfers.sql, models/silver/defi/bridge/celer/silver_bridge__celer_cbridge_send.sql, models/silver/defi/bridge/hop/silver_bridge__hop_ammwrapper.sql, models/silver/defi/bridge/hop/silver_bridge__hop_transfersent.sql, models/silver/defi/bridge/meson/silver_bridge__meson_transfers.sql, models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql, models/silver/defi/dex/balancer/silver_dex__balancer_pools.sql, models/silver/defi/dex/balancer/silver_dex__balancer_swaps.sql, models/silver/defi/dex/curve/silver_dex__curve_pools.sql, models/silver/defi/dex/curve/silver_dex__curve_swaps.sql, models/silver/defi/dex/honeyswap/silver_dex__honeyswap_pools.sql, models/silver/defi/dex/silver_dex__complete_dex_liquidity_pools.sql, models/silver/defi/dex/silver_dex__complete_dex_swaps.sql, models/silver/defi/dex/sushi/silver_dex__sushi_pools.sql, models/silver/defi/dex/swapr/silver_dex__swapr_pools.sql, models/silver/defi/lending/complete_lending/silver__complete_lending_borrows.sql, models/silver/defi/lending/complete_lending/silver__complete_lending_deposits.sql, models/silver/defi/lending/complete_lending/silver__complete_lending_flashloans.sql, models/silver/defi/lending/complete_lending/silver__complete_lending_liquidations.sql, models/silver/defi/lending/complete_lending/silver__complete_lending_repayments.sql, models/silver/defi/lending/complete_lending/silver__complete_lending_withdraws.sql
1. Added heal logic for all complete curated models 
2. Standardized CTE names in complete curated models
3. Rebuilt dex swaps to enable heal logic, cleaned up other defi models
4. Revamped README for vars
5. Changed `HEAL_CURATED_MODEL` var to `HEAL_MODELS`
6. Reduced lookbacks to 4 hours and added `LOOKBACK` var
`dbt run -m models/silver/defi/dex/silver_dex__complete_dex_liquidity_pools.sql models/gold/defi --full-refresh`
=> AN-4280/heal-logic

models/doc_descriptions/transfers/evm_transfers_table_doc.md, models/doc_descriptions/transfers/gno_transfer_table_doc.md, models/gold/core/core__ez_native_transfers.yml, models/gold/core/core__ez_token_transfers.yml, models/gold/core/core__fact_token_transfers.yml
to capture docs updates in snowflake: `dbt run -m models/gold/core/core__ez_native_transfers.sql models/gold/core/core__ez_token_transfers.sql models/gold/core/core__fact_token_transfers.sql`
=> AN-4879/transfers-docs

.github/workflows/dbt_run_adhoc.yml, models/silver/core/silver__receipts.sql, models/silver/core/silver__transactions.sql
`dbt run -m models/silver/core/silver__receipts.sql models/silver/core/silver__transactions.sql`
=> AN-4926/gnosis-transaction-fee-bug-fix

models/silver/protocols/olas/silver_olas__service_checkpoint.sql, models/silver/protocols/olas/silver_olas__service_staking.sql, models/silver/protocols/olas/silver_olas__services_evicted.sql
`dbt run -m models/silver/protocols/olas/silver_olas__service_checkpoint.sql models/silver/protocols/olas/silver_olas__services_evicted.sql models/silver/protocols/olas/silver_olas__service_staking.sql --full-refresh`
=> AN-5053/new-staking-contract

models/silver/defi/lending/aave/silver__aave_repayments.sql
`dbt run -m models/silver/protocols/aave/lending/silver__aave_repayments.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"aave"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_repayments.sql`
=> aave-repay-bug 

models/silver/defi/lending/aave/silver__aave_flashloans.sql, models/silver/protocols/olas/silver_olas__mech_requests.yml
`dbt run -m models/silver/defi/lending/aave/silver__aave_flashloans.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"aave"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_flashloans.sql`
=> aave-olas-fixes

.github/workflows/dbt_run_traces_fix.yml, models/silver/core/silver__fact_traces2.sql, models/silver/core/traces2_fix/silver__fact_traces2_fix.sql
fix the error logic for fact_traces2 and new data
add model to identify historical data that needs fixing
add workflow to run model in step 2
`dbt run -m models/silver/core/traces2_fix/silver__fact_traces2_fix.sql --full-refresh`
=> AN-5669 Add traces2 fix - gnosis 

models/silver/defi/lending/aave/silver__aave_liquidations.sql
`dbt run -m models/silver/defi/lending/aave/silver__aave_liquidations.sql --full-refresh  && dbt run --vars '{"HEAL_MODELS":"aave"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_liquidations.sql`
=> fix-aave-liquidations

models/gold/core/core__fact_event_logs.sql
`dbt run -m models/gold/core/core__fact_event_logs.sql --full-refresh`
=> cap-tx-status 

data/github_actions__workflows.csv
`dbt seed -s github_actions__workflows && dbt run -m models/github_actions --full-refresh && dbt run-operation fsc_utils.create_gha_tasks --vars '{"START_GHA_TASKS":True}'`
=> intraday-sched

data/github_actions__workflows.csv
`dbt seed -s github_actions__workflows && dbt run -m models/github_actions --full-refresh && dbt run-operation fsc_utils.create_gha_tasks --vars '{"START_GHA_TASKS":True}'`
=> decoder-sched

models/silver/defi/lending/aave/silver__aave_tokens.sql, models/silver/defi/lending/spark/silver__spark_tokens.sql
`dbt run -m models/silver/defi/lending/aave models/silver/defi/lending/spark --full-refresh && dbt run --vars '{"HEAL_MODELS":["aave","spark"]}' -m models/silver/defi/lending/complete_lending`
=> AN-5443/aave-token-model-updates
